# Generated by Django 5.2 on 2025-04-25 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='parking_space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='parking.parkingspace'),
        ),
    ]
