const SampleData = [
  {
    name: "Jane Doe",
    university: "Tech University",
    rollNo: "TU2023001",
    branch: "Computer Science",
    section: "A",
    college: "College of Engineering",
    email: "jane.doe@techuniverse.edu",
    batch: 2025,
    cgpa: 3.8,
    backlogs: 0,
    phoneNumber: "+1 (555) 123-4567",
    status: "Applied",
  },
  {
    name: "Jane Doe",
    university: "Tech University",
    rollNo: "TU2023001",
    branch: "Computer Science",
    section: "A",
    college: "College of Engineering",
    email: "jane.doe@techuniverse.edu",
    batch: 2025,
    cgpa: 3.8,
    backlogs: 0,
    contact: "+1 (555) 123-4567",
    gender: "Female",
    status: "Placed",
  },
  {
    name: "John Smith",
    university: "Tech University",
    rollNo: "TU2023002",
    branch: "Electrical Engineering",
    section: "B",
    college: "College of Engineering",
    email: "john.smith@techuniverse.edu",
    batch: 2025,
    cgpa: 3.5,
    backlogs: 1,
    contact: "+1 (555) 234-5678",
    gender: "Male",
    status: "Not Placed",
  },
  {
    name: "Alice Johnson",
    university: "Tech University",
    rollNo: "TU2023003",
    branch: "Mechanical Engineering",
    section: "A",
    college: "College of Engineering",
    email: "alice.johnson@techuniverse.edu",
    batch: 2025,
    cgpa: 3.7,
    backlogs: 0,
    contact: "+1 (555) 345-6789",
    gender: "Female",
    status: "Applied",
  },
  {
    name: "Bob Brown",
    university: "Tech University",
    rollNo: "TU2023004",
    branch: "Civil Engineering",
    section: "C",
    college: "College of Engineering",
    email: "bob.brown@techuniverse.edu",
    batch: 2025,
    cgpa: 3.4,
    backlogs: 2,
    contact: "+1 (555) 456-7890",
    gender: "Male",
    status: "Placed",
  },
  {
    name: "Carol White",
    university: "Tech University",
    rollNo: "TU2023005",
    branch: "Chemical Engineering",
    section: "B",
    college: "College of Engineering",
    email: "carol.white@techuniverse.edu",
    batch: 2025,
    cgpa: 3.6,
    backlogs: 0,
    contact: "+1 (555) 567-8901",
    gender: "Female",
    status: "Not Placed",
  },
  {
    name: "David Black",
    university: "Tech University",
    rollNo: "TU2023006",
    branch: "Computer Science",
    section: "B",
    college: "College of Engineering",
    email: "david.black@techuniverse.edu",
    batch: 2025,
    cgpa: 3.9,
    backlogs: 0,
    contact: "+1 (555) 678-9012",
    gender: "Male",
    status: "Applied",
  },
  {
    name: "Emily Green",
    university: "Tech University",
    rollNo: "TU2023007",
    branch: "Information Technology",
    section: "A",
    college: "College of Engineering",
    email: "emily.green@techuniverse.edu",
    batch: 2025,
    cgpa: 3.3,
    backlogs: 1,
    contact: "+1 (555) 789-0123",
    gender: "Female",
    status: "Placed",
  },
  {
    name: "Frank Harris",
    university: "Tech University",
    rollNo: "TU2023008",
    branch: "Electrical Engineering",
    section: "A",
    college: "College of Engineering",
    email: "frank.harris@techuniverse.edu",
    batch: 2025,
    cgpa: 3.2,
    backlogs: 3,
    contact: "+1 (555) 890-1234",
    gender: "Male",
    status: "Not Placed",
  },
  {
    name: "Grace Lee",
    university: "Tech University",
    rollNo: "TU2023009",
    branch: "Mechanical Engineering",
    section: "C",
    college: "College of Engineering",
    email: "grace.lee@techuniverse.edu",
    batch: 2025,
    cgpa: 3.8,
    backlogs: 0,
    contact: "+1 (555) 901-2345",
    gender: "Female",
    status: "Applied",
  },
  {
    name: "Henry Wilson",
    university: "Tech University",
    rollNo: "TU2023010",
    branch: "Civil Engineering",
    section: "B",
    college: "College of Engineering",
    email: "henry.wilson@techuniverse.edu",
    batch: 2025,
    cgpa: 3.6,
    backlogs: 2,
    contact: "+1 (555) 012-3456",
    gender: "Male",
    status: "Placed",
  },
  {
    name: "Isabella Martinez",
    university: "Tech University",
    rollNo: "TU2023011",
    branch: "Chemical Engineering",
    section: "A",
    college: "College of Engineering",
    email: "isabella.martinez@techuniverse.edu",
    batch: 2025,
    cgpa: 3.7,
    backlogs: 0,
    contact: "+1 (555) 123-4568",
    gender: "Female",
    status: "Not Placed",
  },
  {
    name: "James Anderson",
    university: "Tech University",
    rollNo: "TU2023012",
    branch: "Computer Science",
    section: "C",
    college: "College of Engineering",
    email: "james.anderson@techuniverse.edu",
    batch: 2025,
    cgpa: 3.9,
    backlogs: 1,
    contact: "+1 (555) 234-5679",
    gender: "Male",
    status: "Applied",
  },
  {
    name: "Katherine Thomas",
    university: "Tech University",
    rollNo: "TU2023013",
    branch: "Information Technology",
    section: "B",
    college: "College of Engineering",
    email: "katherine.thomas@techuniverse.edu",
    batch: 2025,
    cgpa: 3.4,
    backlogs: 0,
    contact: "+1 (555) 345-6780",
    gender: "Female",
    status: "Placed",
  },
  {
    name: "Liam Robinson",
    university: "Tech University",
    rollNo: "TU2023014",
    branch: "Electrical Engineering",
    section: "C",
    college: "College of Engineering",
    email: "liam.robinson@techuniverse.edu",
    batch: 2025,
    cgpa: 3.5,
    backlogs: 2,
    contact: "+1 (555) 456-7891",
    gender: "Male",
    status: "Not Placed",
  },
  {
    name: "Mia Clark",
    university: "Tech University",
    rollNo: "TU2023015",
    branch: "Mechanical Engineering",
    section: "B",
    college: "College of Engineering",
    email: "mia.clark@techuniverse.edu",
    batch: 2025,
    cgpa: 3.6,
    backlogs: 1,
    contact: "+1 (555) 567-8902",
    gender: "Female",
    status: "Applied",
  },
  {
    name: "Nathan Lewis",
    university: "Tech University",
    rollNo: "TU2023016",
    branch: "Civil Engineering",
    section: "A",
    college: "College of Engineering",
    email: "nathan.lewis@techuniverse.edu",
    batch: 2025,
    cgpa: 3.2,
    backlogs: 3,
    contact: "+1 (555) 678-9013",
    gender: "Male",
    status: "Placed",
  },
  {
    name: "Olivia Young",
    university: "Tech University",
    rollNo: "TU2023017",
    branch: "Chemical Engineering",
    section: "C",
    college: "College of Engineering",
    email: "olivia.young@techuniverse.edu",
    batch: 2025,
    cgpa: 3.8,
    backlogs: 0,
    contact: "+1 (555) 789-0124",
    gender: "Female",
    status: "Not Placed",
  },
];

export default SampleData;
