# Generated by Django 5.2 on 2025-05-12 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_parkingslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspace',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parkingspace',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
