# Generated by Django 5.2 on 2025-04-25 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('iot', '0001_initial'),
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='iotdevice',
            name='parking_space',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='iot_device', to='parking.parkingspace'),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_data', to='iot.iotdevice'),
        ),
    ]
