// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyCgdzV5Xz0oF-Xkez3E6nT68GzaZAI8zdg",
      authDomain: "quizx-fb763.firebaseapp.com",
      projectId: "quizx-fb763",
      storageBucket: "quizx-fb763.appspot.com",
      messagingSenderId: "647627347924",
      appId: "1:647627347924:web:fbaccef15fb1b680042841");

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHIzxyLdlTQOfIC5QWDGWmzeq77dKaSd8',
    appId: '1:647627347924:android:05e10c777a47b11f042841',
    messagingSenderId: '647627347924',
    projectId: 'quizx-fb763',
    storageBucket: 'quizx-fb763.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgxvokEG6ljiCfGc6mYMrAgJV3snf5KlU',
    appId: '1:647627347924:ios:334734b83ce23245042841',
    messagingSenderId: '647627347924',
    projectId: 'quizx-fb763',
    storageBucket: 'quizx-fb763.appspot.com',
    iosClientId:
        '647627347924-kbbtgj0ntatj9nh6avl8psk6de534src.apps.googleusercontent.com',
    iosBundleId: 'com.codefox.sih_2022',
  );
}
