name: sih_2022
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.6 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.0.0
  get: ^4.6.5
  logger: ^1.0.0
  easy_separator: ^1.0.1
  blurhash_flutter: ^0.1.0
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  flutter_zoom_drawer: ^3.0.3
  liquid_pull_to_refresh: ^3.0.1
  shimmer: ^2.0.0
  flutter_native_splash: ^2.2.7
  cloud_firestore: 3.1.5

  firebase_core: ^1.10.6
  firebase_auth: ^3.3.5
  google_sign_in: ^5.2.1
  firebase_storage: ^10.2.5
  
  

  flutter_local_notifications: ^9.2.0
  path_provider: ^2.0.8
  http: ^0.13.4
  url_launcher: ^6.0.18
  timelines: ^0.1.0
  
  transliteration: ^0.0.6
  
  scoped_model: ^1.1.0

  audioplayers: ^1.0.1
  pie_chart: ^5.3.2
  shared_preferences: ^2.0.15
  iconsax: ^0.0.8
 
  video_player: ^2.4.6
  fl_chart: ^0.55.1
  text_to_speech: ^0.2.3
  translator: ^0.1.7
  flutter_riverpod: ^1.0.4
  
  # Generate Unique Id
  uuid: ^3.0.6

  # Easily detect Swipes
  flutter_swipe_detector: ^2.0.0

  #key-value database which we will use to save game state
  hive: ^2.1.1
  hive_flutter: ^1.1.0

  # Used together with json_serializable to generate fromJson/toJson functions
  json_annotation: ^4.5.0
  syncfusion_flutter_charts: ^20.2.45
  tutorial: ^1.0.9
  # firebase_mlkit_language: ^1.1.3

 
 

  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.1.11

  # Used together with json_serializable to generate fromJson/toJson functions
  json_serializable: ^6.2.0

  

flutter:
  
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/DB/papers/
    - assets/
  
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
  - family: AppIcons
    fonts:
      - asset: assets/icons/AppIcons.ttf
  

  - family: ComicSense
    fonts:
      
      - asset: assets/fonts/ComicSense.ttf  

  - family: Nunito
    fonts:
      
      - asset: assets/fonts/Nunito-Regular.ttf   
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

